/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_user_files_s3_bucket": "buddydrrx",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8533e6c2-1fbd-446c-afe5-3e6e1a9eec87",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tvap4Rrqy",
    "aws_user_pools_web_client_id": "4tcg70oh9qnl7p8afs34m4uu2l",
    "oauth": {},
};


export default awsmobile;
