import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from "../src/Navbar";
import Footer from "../src/Footer";
import Impact from "../src/Impact";
import Investment from "../src/InvestmentPloicy";
import Team from "../src/Team";
import Testimonial from "../src/Testimonial";
import Resources from "../src/Resources";
import WorkTogether from "../src/WorkTogether";

export default function Home() {
    function clickhandler(){

    }
  return (
    <div className={styles.Root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className={styles.mainContainer}>
            <div className={styles.top_contianer}>
                <Navbar clickhandler={clickhandler}/>
                <div className={styles.top_contianer_image}></div>
                <div className={styles.top_contianer_content}>
                    <div className={styles.top_contianer_content_title}>
                        <div className={styles.hero_heading}>
                            We build the future with you
                        </div>
                        <div className={styles.hero_subhead}>
                            Early backers of remarkable teams through their astronomical ambitions.
                            We invest, incubate, and build companies in exponential tech. We strive to be the best fit for you on day 1, and the best fit for you at the end of the horizon.
                        </div>
                        <div className={styles.start_now} onClick={clickhandler}>
                            <div className={styles.text} >
                                Apply Now
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Impact />
            <Investment />
            <Team />
            <Testimonial />
            {/*<Resources />*/}
            <WorkTogether clickhandler={clickhandler} />
        </div>

      <Footer />
    </div>
  )
}
